server:
  port: 8082 # Port where the Payment Service will run

spring:
  application:
    name: payment-service # This name will be used to register with Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of your Eureka Server
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always