server:
  port: 8081 # Port where the Order Service will run

spring:
  application:
    name: order-service # This name will be used to register the service in Eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of your Eureka Server
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always